// <auto-generated />
namespace THE_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addproposalsatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addproposalsatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202106020221050_add-proposal-satus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
