// <auto-generated />
namespace THE_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addfristlastname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfristlastname));
        
        string IMigrationMetadata.Id
        {
            get { return "202105281625572_add-frist-last-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
