// <auto-generated />
namespace THE_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Newpost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Newpost));
        
        string IMigrationMetadata.Id
        {
            get { return "202105301542311_Newpost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
